### ISSUE TITLE
include_path vs include_paths

### ISSUE THREAD

**Issue by mortenpi** [piever/Sass.jl#12]
For setting the include paths, the documentation

https://github.com/piever/Sass.jl/blob/f627a99b250f5b56876cef4812d247a15f2ea72b/src/julian_api.jl#L35

disagrees with the implementation

https://github.com/piever/Sass.jl/blob/f627a99b250f5b56876cef4812d247a15f2ea72b/src/julian_api.jl#L11

As `libsass` seems to have `s` at the end, I guess the implementation should be changed to `:include_paths => sass_option_set_include_paths`?

**Comment by piever** [comment]
If I remember correctly, the rationale was that the C API has `include_path` to pass one string (of either one path, or many "colon separated" paths), and `include_paths` to pass an array of strings. At least, that's what I understood from reading [here](https://github.com/sass/libsass/blob/master/docs/api-context.md). At the time I thought that this API was a bit odd.

Possible options:
1. Stick to C API and have different keywords for one string or many
2. Choose `include_path` for both one string or many
3. Choose `include_paths` for both one string or many
4. Allow either  `include_path` or  `include_paths` for both one string or many

Which makes the most sense to you? I suspect 3 is the Julian way, as in the case of "one or many" the default is the plural. OTOH it may be not ideal to have `include_paths` and `plugin_paths`, but `input_path` and `output_path`.

**Comment by mortenpi** [comment]
Sorry for forgetting to reply to this. My feeling is that since the keyword is directly related to the `sass_option_set_include_path` function, it would make sense to keep it `include_path`.

I didn't read the C code, but looking at the C API, my hunch is that `include_paths` is just an internal helper variable and is kept synced with `include_path`. As far as I can tell, `include_path` can contain either a single path or many (colon-separated) and in either case you should set it with `sass_option_set_include_path`.

**Comment by piever** [comment]
Makes sense, I also prefer changing the documentation rather than the implementation. Thanks for making the PR!
